package org.wudang.model;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.emailstatus
     *
     * @mbggenerated
     */
    private Boolean emailstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.avatarstatus
     *
     * @mbggenerated
     */
    private Boolean avatarstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.adminid
     *
     * @mbggenerated
     */
    private Boolean adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.groupid
     *
     * @mbggenerated
     */
    private Short groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.groupexpiry
     *
     * @mbggenerated
     */
    private Integer groupexpiry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.extgroupids
     *
     * @mbggenerated
     */
    private String extgroupids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.regdate
     *
     * @mbggenerated
     */
    private Integer regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.credits
     *
     * @mbggenerated
     */
    private Integer credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.newpm
     *
     * @mbggenerated
     */
    private Short newpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.newprompt
     *
     * @mbggenerated
     */
    private Short newprompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_common_member.onlyacceptfriendpm
     *
     * @mbggenerated
     */
    private Boolean onlyacceptfriendpm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.uid
     *
     * @return the value of pre_common_member.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.uid
     *
     * @param uid the value for pre_common_member.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.email
     *
     * @return the value of pre_common_member.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.email
     *
     * @param email the value for pre_common_member.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.username
     *
     * @return the value of pre_common_member.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.username
     *
     * @param username the value for pre_common_member.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.password
     *
     * @return the value of pre_common_member.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.password
     *
     * @param password the value for pre_common_member.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.status
     *
     * @return the value of pre_common_member.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.status
     *
     * @param status the value for pre_common_member.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.emailstatus
     *
     * @return the value of pre_common_member.emailstatus
     *
     * @mbggenerated
     */
    public Boolean getEmailstatus() {
        return emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.emailstatus
     *
     * @param emailstatus the value for pre_common_member.emailstatus
     *
     * @mbggenerated
     */
    public void setEmailstatus(Boolean emailstatus) {
        this.emailstatus = emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.avatarstatus
     *
     * @return the value of pre_common_member.avatarstatus
     *
     * @mbggenerated
     */
    public Boolean getAvatarstatus() {
        return avatarstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.avatarstatus
     *
     * @param avatarstatus the value for pre_common_member.avatarstatus
     *
     * @mbggenerated
     */
    public void setAvatarstatus(Boolean avatarstatus) {
        this.avatarstatus = avatarstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.adminid
     *
     * @return the value of pre_common_member.adminid
     *
     * @mbggenerated
     */
    public Boolean getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.adminid
     *
     * @param adminid the value for pre_common_member.adminid
     *
     * @mbggenerated
     */
    public void setAdminid(Boolean adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.groupid
     *
     * @return the value of pre_common_member.groupid
     *
     * @mbggenerated
     */
    public Short getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.groupid
     *
     * @param groupid the value for pre_common_member.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(Short groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.groupexpiry
     *
     * @return the value of pre_common_member.groupexpiry
     *
     * @mbggenerated
     */
    public Integer getGroupexpiry() {
        return groupexpiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.groupexpiry
     *
     * @param groupexpiry the value for pre_common_member.groupexpiry
     *
     * @mbggenerated
     */
    public void setGroupexpiry(Integer groupexpiry) {
        this.groupexpiry = groupexpiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.extgroupids
     *
     * @return the value of pre_common_member.extgroupids
     *
     * @mbggenerated
     */
    public String getExtgroupids() {
        return extgroupids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.extgroupids
     *
     * @param extgroupids the value for pre_common_member.extgroupids
     *
     * @mbggenerated
     */
    public void setExtgroupids(String extgroupids) {
        this.extgroupids = extgroupids == null ? null : extgroupids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.regdate
     *
     * @return the value of pre_common_member.regdate
     *
     * @mbggenerated
     */
    public Integer getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.regdate
     *
     * @param regdate the value for pre_common_member.regdate
     *
     * @mbggenerated
     */
    public void setRegdate(Integer regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.credits
     *
     * @return the value of pre_common_member.credits
     *
     * @mbggenerated
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.credits
     *
     * @param credits the value for pre_common_member.credits
     *
     * @mbggenerated
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.newpm
     *
     * @return the value of pre_common_member.newpm
     *
     * @mbggenerated
     */
    public Short getNewpm() {
        return newpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.newpm
     *
     * @param newpm the value for pre_common_member.newpm
     *
     * @mbggenerated
     */
    public void setNewpm(Short newpm) {
        this.newpm = newpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.newprompt
     *
     * @return the value of pre_common_member.newprompt
     *
     * @mbggenerated
     */
    public Short getNewprompt() {
        return newprompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.newprompt
     *
     * @param newprompt the value for pre_common_member.newprompt
     *
     * @mbggenerated
     */
    public void setNewprompt(Short newprompt) {
        this.newprompt = newprompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_common_member.onlyacceptfriendpm
     *
     * @return the value of pre_common_member.onlyacceptfriendpm
     *
     * @mbggenerated
     */
    public Boolean getOnlyacceptfriendpm() {
        return onlyacceptfriendpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_common_member.onlyacceptfriendpm
     *
     * @param onlyacceptfriendpm the value for pre_common_member.onlyacceptfriendpm
     *
     * @mbggenerated
     */
    public void setOnlyacceptfriendpm(Boolean onlyacceptfriendpm) {
        this.onlyacceptfriendpm = onlyacceptfriendpm;
    }
}