package org.wudang.model;

import java.util.ArrayList;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public MemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIsNull() {
            addCriterion("emailstatus is null");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIsNotNull() {
            addCriterion("emailstatus is not null");
            return (Criteria) this;
        }

        public Criteria andEmailstatusEqualTo(Boolean value) {
            addCriterion("emailstatus =", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotEqualTo(Boolean value) {
            addCriterion("emailstatus <>", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusGreaterThan(Boolean value) {
            addCriterion("emailstatus >", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("emailstatus >=", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusLessThan(Boolean value) {
            addCriterion("emailstatus <", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusLessThanOrEqualTo(Boolean value) {
            addCriterion("emailstatus <=", value, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusIn(List<Boolean> values) {
            addCriterion("emailstatus in", values, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotIn(List<Boolean> values) {
            addCriterion("emailstatus not in", values, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusBetween(Boolean value1, Boolean value2) {
            addCriterion("emailstatus between", value1, value2, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andEmailstatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("emailstatus not between", value1, value2, "emailstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusIsNull() {
            addCriterion("avatarstatus is null");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusIsNotNull() {
            addCriterion("avatarstatus is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusEqualTo(Boolean value) {
            addCriterion("avatarstatus =", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusNotEqualTo(Boolean value) {
            addCriterion("avatarstatus <>", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusGreaterThan(Boolean value) {
            addCriterion("avatarstatus >", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("avatarstatus >=", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusLessThan(Boolean value) {
            addCriterion("avatarstatus <", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusLessThanOrEqualTo(Boolean value) {
            addCriterion("avatarstatus <=", value, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusIn(List<Boolean> values) {
            addCriterion("avatarstatus in", values, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusNotIn(List<Boolean> values) {
            addCriterion("avatarstatus not in", values, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusBetween(Boolean value1, Boolean value2) {
            addCriterion("avatarstatus between", value1, value2, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAvatarstatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("avatarstatus not between", value1, value2, "avatarstatus");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminid is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminid is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(Boolean value) {
            addCriterion("adminid =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(Boolean value) {
            addCriterion("adminid <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(Boolean value) {
            addCriterion("adminid >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("adminid >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(Boolean value) {
            addCriterion("adminid <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(Boolean value) {
            addCriterion("adminid <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<Boolean> values) {
            addCriterion("adminid in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<Boolean> values) {
            addCriterion("adminid not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(Boolean value1, Boolean value2) {
            addCriterion("adminid between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("adminid not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNull() {
            addCriterion("groupid is null");
            return (Criteria) this;
        }

        public Criteria andGroupidIsNotNull() {
            addCriterion("groupid is not null");
            return (Criteria) this;
        }

        public Criteria andGroupidEqualTo(Short value) {
            addCriterion("groupid =", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotEqualTo(Short value) {
            addCriterion("groupid <>", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThan(Short value) {
            addCriterion("groupid >", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidGreaterThanOrEqualTo(Short value) {
            addCriterion("groupid >=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThan(Short value) {
            addCriterion("groupid <", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidLessThanOrEqualTo(Short value) {
            addCriterion("groupid <=", value, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidIn(List<Short> values) {
            addCriterion("groupid in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotIn(List<Short> values) {
            addCriterion("groupid not in", values, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidBetween(Short value1, Short value2) {
            addCriterion("groupid between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupidNotBetween(Short value1, Short value2) {
            addCriterion("groupid not between", value1, value2, "groupid");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryIsNull() {
            addCriterion("groupexpiry is null");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryIsNotNull() {
            addCriterion("groupexpiry is not null");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryEqualTo(Integer value) {
            addCriterion("groupexpiry =", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryNotEqualTo(Integer value) {
            addCriterion("groupexpiry <>", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryGreaterThan(Integer value) {
            addCriterion("groupexpiry >", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryGreaterThanOrEqualTo(Integer value) {
            addCriterion("groupexpiry >=", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryLessThan(Integer value) {
            addCriterion("groupexpiry <", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryLessThanOrEqualTo(Integer value) {
            addCriterion("groupexpiry <=", value, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryIn(List<Integer> values) {
            addCriterion("groupexpiry in", values, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryNotIn(List<Integer> values) {
            addCriterion("groupexpiry not in", values, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryBetween(Integer value1, Integer value2) {
            addCriterion("groupexpiry between", value1, value2, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andGroupexpiryNotBetween(Integer value1, Integer value2) {
            addCriterion("groupexpiry not between", value1, value2, "groupexpiry");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsIsNull() {
            addCriterion("extgroupids is null");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsIsNotNull() {
            addCriterion("extgroupids is not null");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsEqualTo(String value) {
            addCriterion("extgroupids =", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsNotEqualTo(String value) {
            addCriterion("extgroupids <>", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsGreaterThan(String value) {
            addCriterion("extgroupids >", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsGreaterThanOrEqualTo(String value) {
            addCriterion("extgroupids >=", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsLessThan(String value) {
            addCriterion("extgroupids <", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsLessThanOrEqualTo(String value) {
            addCriterion("extgroupids <=", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsLike(String value) {
            addCriterion("extgroupids like", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsNotLike(String value) {
            addCriterion("extgroupids not like", value, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsIn(List<String> values) {
            addCriterion("extgroupids in", values, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsNotIn(List<String> values) {
            addCriterion("extgroupids not in", values, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsBetween(String value1, String value2) {
            addCriterion("extgroupids between", value1, value2, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andExtgroupidsNotBetween(String value1, String value2) {
            addCriterion("extgroupids not between", value1, value2, "extgroupids");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNull() {
            addCriterion("regdate is null");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNotNull() {
            addCriterion("regdate is not null");
            return (Criteria) this;
        }

        public Criteria andRegdateEqualTo(Integer value) {
            addCriterion("regdate =", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotEqualTo(Integer value) {
            addCriterion("regdate <>", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThan(Integer value) {
            addCriterion("regdate >", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("regdate >=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThan(Integer value) {
            addCriterion("regdate <", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThanOrEqualTo(Integer value) {
            addCriterion("regdate <=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateIn(List<Integer> values) {
            addCriterion("regdate in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotIn(List<Integer> values) {
            addCriterion("regdate not in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateBetween(Integer value1, Integer value2) {
            addCriterion("regdate between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotBetween(Integer value1, Integer value2) {
            addCriterion("regdate not between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNull() {
            addCriterion("credits is null");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNotNull() {
            addCriterion("credits is not null");
            return (Criteria) this;
        }

        public Criteria andCreditsEqualTo(Integer value) {
            addCriterion("credits =", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotEqualTo(Integer value) {
            addCriterion("credits <>", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThan(Integer value) {
            addCriterion("credits >", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThanOrEqualTo(Integer value) {
            addCriterion("credits >=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThan(Integer value) {
            addCriterion("credits <", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThanOrEqualTo(Integer value) {
            addCriterion("credits <=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsIn(List<Integer> values) {
            addCriterion("credits in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotIn(List<Integer> values) {
            addCriterion("credits not in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsBetween(Integer value1, Integer value2) {
            addCriterion("credits between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotBetween(Integer value1, Integer value2) {
            addCriterion("credits not between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andNewpmIsNull() {
            addCriterion("newpm is null");
            return (Criteria) this;
        }

        public Criteria andNewpmIsNotNull() {
            addCriterion("newpm is not null");
            return (Criteria) this;
        }

        public Criteria andNewpmEqualTo(Short value) {
            addCriterion("newpm =", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmNotEqualTo(Short value) {
            addCriterion("newpm <>", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmGreaterThan(Short value) {
            addCriterion("newpm >", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmGreaterThanOrEqualTo(Short value) {
            addCriterion("newpm >=", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmLessThan(Short value) {
            addCriterion("newpm <", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmLessThanOrEqualTo(Short value) {
            addCriterion("newpm <=", value, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmIn(List<Short> values) {
            addCriterion("newpm in", values, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmNotIn(List<Short> values) {
            addCriterion("newpm not in", values, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmBetween(Short value1, Short value2) {
            addCriterion("newpm between", value1, value2, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpmNotBetween(Short value1, Short value2) {
            addCriterion("newpm not between", value1, value2, "newpm");
            return (Criteria) this;
        }

        public Criteria andNewpromptIsNull() {
            addCriterion("newprompt is null");
            return (Criteria) this;
        }

        public Criteria andNewpromptIsNotNull() {
            addCriterion("newprompt is not null");
            return (Criteria) this;
        }

        public Criteria andNewpromptEqualTo(Short value) {
            addCriterion("newprompt =", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptNotEqualTo(Short value) {
            addCriterion("newprompt <>", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptGreaterThan(Short value) {
            addCriterion("newprompt >", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptGreaterThanOrEqualTo(Short value) {
            addCriterion("newprompt >=", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptLessThan(Short value) {
            addCriterion("newprompt <", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptLessThanOrEqualTo(Short value) {
            addCriterion("newprompt <=", value, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptIn(List<Short> values) {
            addCriterion("newprompt in", values, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptNotIn(List<Short> values) {
            addCriterion("newprompt not in", values, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptBetween(Short value1, Short value2) {
            addCriterion("newprompt between", value1, value2, "newprompt");
            return (Criteria) this;
        }

        public Criteria andNewpromptNotBetween(Short value1, Short value2) {
            addCriterion("newprompt not between", value1, value2, "newprompt");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmIsNull() {
            addCriterion("onlyacceptfriendpm is null");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmIsNotNull() {
            addCriterion("onlyacceptfriendpm is not null");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmEqualTo(Boolean value) {
            addCriterion("onlyacceptfriendpm =", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmNotEqualTo(Boolean value) {
            addCriterion("onlyacceptfriendpm <>", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmGreaterThan(Boolean value) {
            addCriterion("onlyacceptfriendpm >", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmGreaterThanOrEqualTo(Boolean value) {
            addCriterion("onlyacceptfriendpm >=", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmLessThan(Boolean value) {
            addCriterion("onlyacceptfriendpm <", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmLessThanOrEqualTo(Boolean value) {
            addCriterion("onlyacceptfriendpm <=", value, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmIn(List<Boolean> values) {
            addCriterion("onlyacceptfriendpm in", values, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmNotIn(List<Boolean> values) {
            addCriterion("onlyacceptfriendpm not in", values, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmBetween(Boolean value1, Boolean value2) {
            addCriterion("onlyacceptfriendpm between", value1, value2, "onlyacceptfriendpm");
            return (Criteria) this;
        }

        public Criteria andOnlyacceptfriendpmNotBetween(Boolean value1, Boolean value2) {
            addCriterion("onlyacceptfriendpm not between", value1, value2, "onlyacceptfriendpm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_common_member
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pre_common_member
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}